-keep class com.shslab.app.** { *; }
-keep class org.nanohttpd.** { *; }
-dontwarn org.nanohttpd.**
-keepattributes Signature
-keepattributes *Annotation*
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
